Repository Foundation-19/Hail-Mary, pull requests merged in 2023-08, with the labels that each got.

#22 S.P.E.C.I.A.L. implementation
  code/_onclick/item_attack.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/carbon_sprint.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/life.dm
  code/modules/mob/say_vr.dm
  code/modules/mob/special_stats.dm
  code/modules/projectiles/ammunition/_firing.dm
  code/modules/projectiles/gun.dm
  hailmary.dme
Labels: feature addition

#10 Server Config Update
  config/config.txt
  config/custom_roundstart_items.txt
  config/game_options.txt
  config/in_character_filter.txt
  config/loadout_config.txt
  config/motd.txt
  config/title_screens/images/title1.png
  interface/skin.dmf
Labels: enhancement, work-in-progress, feature removal, config changes

#24 gun sprite and combat overhaul
  code/__DEFINES/combat.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/launchers.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
  code/modules/projectiles/guns/hoboguns.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  icons/obj/guns/energy.dmi
  icons/obj/guns/projectile.dmi
Labels: item addition, to be tested

#26 Base PAs
  code/modules/clothing/spacesuits/power_armor.dm
  code/modules/clothing/spacesuits/power_armor_parts.dm
  fallout/icons/objects/pa_items.dmi
  icons/mob/large-worn-icons/armor.dmi
  icons/mob/large-worn-icons/head.dmi
Labels: feature addition, work-in-progress

#40 Shit removal
  code/__DEFINES/atom_hud.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/living.dm
  code/modules/mob/logout.dm
Labels: bug fix
