Repository Foundation-19/Hail-Mary, pull requests merged in 2024-06, with the labels that each got.

#161 Replaces the unused Khan base with a new mutant base
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Labels: test merged, map changes, faction changes

#168 Medical Officer Back Baby
  code/modules/jobs/job_types/ncr.dm
Labels: test merged, feature addition, config changes, faction changes, balance

#169 Adds a ctrl + click spawn method
  code/_onclick/observer.dm
  code/game/objects/items/binoculars.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/spells/spell_types/return_spell.dm
  hailmary.dme
Labels: enhancement, test merged, bug fix, feature addition

#181 Unfuck-stim-Hemo
  code/modules/reagents/chemistry/recipes/medicine.dm
  fallout/reagents/medicines.dm
Labels: test merged, bug fix, balance

#182 Removes more ways for slimes and morphs to be spawned
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
  code/modules/reagents/reagent_containers/syringes.dm
Labels: test merged, bug fix, feature removal, balance

#189 Removing the condom aka rubber quickfix
  code/__DEFINES/combat.dm
  code/modules/research/designs/ammolathe_designs.dm
Labels: test merged, bug fix, balance

#178 Wire Monkey + Pierce Immune Trait Fixes
  code/__DEFINES/traits.dm
  code/datums/components/caltrop.dm
  code/datums/traits/good.dm
Labels: bug fix, balance

#184 Laz Injector nerf
  code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
  code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
  code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
  code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Labels: test merged, bug fix, feature removal, balance

#132 renables radio
  code/controllers/subsystem/jukeboxes.dm
  code/datums/components/armor_plate.dm
  code/datums/components/crafting/recipes/recipes_explosives.dm
  code/game/machinery/dance_machine.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/living/carbon/carbon_sprint.dm
  fallout/obj/structures/simple_door.dm
  hailmary.dme
  icons/obj/guns/projectile.dmi
  modular_BD2/blacksmith/code/anvil.dm
  modular_BD2/general/sound/Amore.ogg
  modular_BD2/general/sound/Jailhouse.ogg
  modular_BD2/general/sound/Sixteen.ogg
  modular_BD2/general/sound/cursed.ogg
  modular_big-iron/code/game/machinery/radio_station.dm
  modular_big-iron/code/game/tracks.dm
Labels: help wanted, big iron port

#174 Energy WeaponRebalance
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/cargo/packs/security.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
Labels: test merged, map changes, hot topic, balance

#190 Lets staff have funny ghosts
  code/modules/client/preferences.dm
Labels: enhancement, test merged, feature addition, sprites

#192 Fixes disconnected player timers not showing
  code/modules/mob/living/carbon/human/examine.dm
Labels: documentation, test merged, bug fix

#193 Adds a random roman name button
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/names.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/mob/living/carbon/human/species.dm
  strings/names/firstlegion_female.txt
  strings/names/firstlegion_male.txt
  strings/names/lastlegion.txt
Labels: documentation, enhancement, test merged, feature addition, faction changes

#188 Edits a bunch of flavor text for reagents
  fallout/reagents/alcohol.dm
  fallout/reagents/drinks.dm
  fallout/reagents/drugs.dm
  fallout/reagents/juices.dm
  fallout/reagents/medicines.dm
  fallout/reagents/other_reagents.dm
  fallout/reagents/teas.dm
Labels: documentation, test merged, bug fix
