Repository Foundation-19/Hail-Mary, pull requests merged in 2024-11, with the labels that each got.

#251 Reverts some sprites to their old version, but not all.
  icons/obj/guns/projectile.dmi
Labels: sprites

#249 New In-Hand Sprites for G11, Handmade Rifle variants, and pre-existing guns
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/energy/laser.dm
  icons/fallout/mobs/humans/fallout_bos_npc.dmi
  icons/fallout/mobs/humans/fallout_enclave_npc.dmi
  icons/fallout/mobs/humans/fallout_gla_npc.dmi
  icons/fallout/mobs/humans/fallout_glaspec_npc.dmi
  icons/fallout/mobs/humans/fallout_greenelement_npc.dmi
  icons/fallout/mobs/humans/fallout_junker_npc.dmi
  icons/fallout/mobs/humans/fallout_legion_npc.dmi
  icons/fallout/mobs/humans/fallout_ncr_npc.dmi
  icons/fallout/mobs/humans/fallout_sov_npc.dmi
  icons/fallout/mobs/humans/fallout_sovspec.dmi
  icons/fallout/mobs/humans/fallout_sovspec_dead.dmi
  icons/fallout/mobs/robots/fallout_hades_npc.dmi
  icons/fallout/mobs/robots/fallout_junker_towermarkii.dmi
  icons/fallout/mobs/robots/fallout_npc_institute.dmi
  icons/fallout/mobs/supermutant_specdead.dmi
  icons/fallout/mobs/supermutantspec.dmi
  icons/fallout/onmob/weapons/guns_lefthand.dmi
  icons/fallout/onmob/weapons/guns_righthand.dmi
Labels: sprites

#220 Baltimore small Map fixes + bos - Enclave base fixes
  _maps/map_files/Baltimore/baltimore_surface.dmm
  _maps/map_files/Baltimore/baltimore_upperlevel.dmm
Labels: map changes - baltimore

#250 gives orator and barons some caps
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
Labels: balance

#256 I HATE VERTIBOMBING SO MUCH aka vertibombing removal
  code/datums/components/crafting/recipes/vehicle_parts.dm
  code/game/mecha/equipment/weapons/weapons.dm
Labels: feature removal, balance

#254 Adds 250 RPM, changes the R82, Handmade Assault Carbine
  code/__DEFINES/combat.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  fallout/eris/code/gun_firemode.dm
Labels: enhancement, balance

#260 Freerunning to Freefaller
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/traits/good.dm
  code/modules/mob/living/living.dm
Labels: feature addition, feature removal, balance

#262 AC Tiers Update - New Line Math
  code/__DEFINES/armor.dm
Labels: balance

#263 Harsh Rocks
  code/game/turfs/simulated/minerals.dm
  fallout/turf/walls.dm
  icons/fallout/turfs/mining.dmi
  icons/obj/rails.dmi
  icons/turf/mining.dmi
Labels: Fluff

#253 BAltimore changes
  _maps/map_files/Baltimore/baltimore_surface.dmm
Labels: work-in-progress, map changes - baltimore

#270 Language Organization + Addition
  code/datums/traits/good.dm
  code/datums/traits/neutral.dm
  code/modules/language/aphasia.dm
  code/modules/language/beachbum.dm
  code/modules/language/codespeak.dm
  code/modules/language/common.dm
  code/modules/language/draconic.dm
  code/modules/language/drone.dm
  code/modules/language/dwarven.dm
  code/modules/language/f13languages.dm
  code/modules/language/machine.dm
  code/modules/language/monkey.dm
  code/modules/language/mushroom.dm
  code/modules/language/narsian.dm
  code/modules/language/ratvarian.dm
  code/modules/language/slime.dm
  code/modules/language/ss13languages.dm
  code/modules/language/swarmer.dm
  code/modules/language/sylvan.dm
  code/modules/language/vampiric.dm
  code/modules/language/voltaic.dm
  code/modules/language/wayfarer.dm
  code/modules/language/xenocommon.dm
  code/modules/surgery/organs/tongue.dm
  hailmary.dme
  icons/misc/language.dmi
Labels: feature addition, Fluff

#273 Reverts: Voting
  code/__DEFINES/vote.dm
Labels: config changes

#257 Adds ID Card terminals in Towns (Eastwood and Locust point)
  _maps/map_files/Baltimore/baltimore_upperlevel.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/game/machinery/computer/card.dm
  code/game/objects/items/circuitboards/computer_circuitboards.dm
  code/modules/jobs/access.dm
Labels: map changes - pahrump, feature addition, map changes - baltimore

#244 Port of the Big Iron Paper Work + remove coyote folder round persistance
  code/controllers/subsystem/persistence.dm
  code/datums/traits/neutral.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/paperwork/carbonpaper.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/contract.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/handlabeler.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_cutter.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/paperwork/paperbin.dm
  code/modules/paperwork/paperplane.dm
  code/modules/paperwork/pen.dm
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/stamps.dm
  code/modules/paperwork/ticketmachine.dm
Labels: feature addition, work-in-progress

#243 Overall base fixes and addition
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Labels: map changes - pahrump

#267 Craftable cars rudimentary system + Makes all vechicles no longer phazon + Makes them impossible to carry weapons + Trunks.
  _maps/map_files/Baltimore/baltimore_surface.dmm
  _maps/map_files/Baltimore/baltimore_upperlevel.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/__DEFINES/construction.dm
  code/_onclick/adjacent.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes/vehicle_crafts.dm
  code/datums/components/crafting/recipes/vehicle_parts.dm
  code/datums/components/storage/concrete/trunk.dm
  code/game/atoms_movement.dm
  code/game/mecha/combat/combatvehicle.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/game/mecha/equipment/tools/work_tools.dm
  code/game/mecha/mecha.dm
  code/game/mecha/medical_tools.dm
  code/game/mecha/other_tools.dm
  code/game/mecha/working/normalvehicle.dm
  code/game/objects/items/miscellaneous.dm
  code/modules/vehicles/rubbish.dm
  fallout/code/modules/client/loadout/hands.dm
  hailmary.dme
  icons/fallout/vehicles/medium_vehicles.dmi
Labels: enhancement, map changes - pahrump, balance, sprites

#280 Map Fix: Upper Reallignment 2
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
Labels: bug fix, map changes - pahrump

#276 Loadout + Trait Changes + Sugar OD 'rework'
  code/datums/traits/negative.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
Labels: faction changes, Fluff

#258 10mm Drum Magazine
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/granters.dm
  code/modules/projectiles/boxes_magazines/external/pistol.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  icons/fallout/objects/guns/ammo.dmi
  icons/obj/guns/projectile.dmi
Labels: sprites, Fluff

#284 Sprite Addition: Antivenom
  code/modules/reagents/reagent_containers/pill.dm
  icons/fallout/objects/medicine/drugs.dmi
Labels: sprites, Fluff

#281 Mirror Addition + Wasteland Spawner: Grand Daddy Mirror + Moves wasteland spawner into the tunnels
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/game/objects/structures/mirror.dm
  icons/obj/watercloset.dmi
Labels: map changes - pahrump, Fluff
