Repository Foundation-19/Hail-Mary, pull requests merged in 2024-12, with the labels that each got.

#279 Opens more roles to Super Mutants
  code/modules/mob/living/carbon/human/species_types/supermutant.dm
Labels: work-in-progress, faction changes

#246 Ports Big Iron's Thirst mecanics in Hailmary code
  _maps/map_files/Baltimore/baltimore_surface.dmm
  _maps/map_files/Baltimore/baltimore_underground.dmm
  _maps/map_files/Baltimore/baltimore_upperlevel.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/__DEFINES/mobs.dm
  code/_onclick/hud/alert.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  fallout/reagents/alcohol.dm
  fallout/reagents/drinks.dm
  fallout/reagents/juices.dm
  icons/mob/screen_alert.dmi
Labels: hot topic, big iron port

#271 Custom Loadout Overhaul
  code/__DEFINES/loadout.dm
  fallout/code/modules/client/loadout/glasses.dm
  fallout/code/modules/client/loadout/gloves.dm
  fallout/code/modules/client/loadout/hands.dm
  fallout/code/modules/client/loadout/head.dm
  fallout/code/modules/client/loadout/mask.dm
  fallout/code/modules/client/loadout/neck.dm
  fallout/code/modules/client/loadout/shoes.dm
  fallout/code/modules/client/loadout/suit.dm
  fallout/code/modules/client/loadout/uniform.dm
Labels: enhancement, test merged

#264 GET READY FOR A FISTING aka 2handed melee gloves.
  code/datums/components/crafting/recipes/recipes_forge.dm
  code/game/objects/items/melee/f13onehanded.dm
  code/game/objects/items/melee/f13powerfist.dm
  icons/fallout/objects/melee/melee.dmi
  icons/fallout/onmob/clothes/hand.dmi
Labels: feature addition, work-in-progress
