Repository Foundation-19/Hail-Mary, pull requests merged in 2024-03, with the labels that each got.

#60 bos rework
  .vscode/settings.json
  _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_whitelist.dm
  code/modules/jobs/jobs.dm
Labels: faction changes

#63 Changes all Refs of 'Sunset' to 'AB'
  _maps/_basemap.dm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  _maps/map_files/Pahrump-AB/job_changes.dm
  code/modules/jobs/map_changes/map_changes.dm
  code/modules/mapping/map_config.dm
Labels: config changes

#66 Legion and NCR armor
  code/__DEFINES/armor.dm
  code/game/objects/items/modkit.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/suits/arfsuits.dm
  code/modules/clothing/suits/arfsuits_unused.dm
  code/modules/clothing/suits/f13factionarmor.dm
  code/modules/jobs/job_types/ncr.dm
Labels: bug fix, faction changes

#68 Rudimentary Map Fixes - Starter Edition
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Labels: map changes

#71 returning crit to normal values
  code/__DEFINES/combat.dm
Labels: bug fix, balance

#65 Flag Readdition: Flags are back
  code/game/objects/items/fallout13misc.dm
  icons/obj/flags.dmi
Labels: feature addition

#73 fixes gauss rifle sprites
  code/modules/projectiles/guns/ballistic/automatic.dm
Labels: bug fix, sprites

#74 Medical Addition: Tribal + Legion Medical
  code/game/machinery/defibrillator_mount.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/reagents/reagent_containers/medspray.dm
  code/modules/surgery/tools.dm
  icons/mob/inhands/equipment/backpack_lefthand.dmi
  icons/mob/inhands/equipment/backpack_righthand.dmi
  icons/obj/chemical.dmi
  icons/obj/iv_drip.dmi
  icons/obj/machines/defib_mount.dmi
  icons/obj/storage.dmi
  icons/obj/surgery.dmi
Labels: feature addition, big iron port, sprites

#76 Fish Addition: Shark replaces Eel
  code/game/objects/items/fish.dm
  code/game/objects/items/fishingrod.dm
Labels: balance

#72 getting rid of some of the ridiculous waster kits
  code/game/objects/items/loadout_beacons.dm
Labels: balance

#79 Map fixes
  _maps/map_files/Pahrump-AB/Dungeons.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Labels: map changes

#81 Med, drinks, plants: Bloodleaf seeds, drink, tea and Bitters.
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/modules/food_and_drinks/recipes/drinks/drinks_fallout.dm
  code/modules/hydroponics/grown/bloodleaf.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/paperwork/paper_premade.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/pill.dm
  fallout/reagents/drinks.dm
  fallout/reagents/medicines.dm
  fallout/reagents/teas.dm
  icons/fallout/objects/storage.dmi
  icons/obj/drinks.dmi
  icons/obj/hydroponics/growing_flowers.dmi
  icons/obj/hydroponics/seeds.dmi
Labels: bug fix, feature addition, item addition

#67 Makes sentinel more than just reskinned elder
  code/modules/jobs/job_types/bos.dm
Labels: opinion

#77 Replace all mention of Nash back to Eastwood + Adds a Extra bartender slot
  code/modules/jobs/job_types/oasis.dm
  code/modules/jobs/jobs.dm
Labels: needs work, faction changes

#78 fixing the no pa spawn shit + bug fixes
  _maps/map_files/Pahrump-AB/Dungeons.dmm
  code/modules/jobs/job_types/bos.dm
  icons/fallout/objects/guns/ballistic.dmi
Labels: bug fix, work-in-progress
