Repository Foundation-19/Hail-Mary, pull requests merged in 2024-09, with the labels that each got.

#146 Wasteland Flipper: Lamp post repair DLC
  _maps/map_files/Fortress Nash/FortNash1.dmm
  _maps/map_files/Fortress Nash/FortNashUpper1.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  _maps/map_files/Pahrump-Old/Pahrump-Sunset.dmm
  _maps/map_files/Pahrump-Sunset - Backup/Pahrump-Sunset.dmm
  _maps/map_files/Pahrump-Sunset - Backup/RedRiver.dmm
  _maps/map_files/Pahrump-Sunset - Backup/RockSprings.dmm
  _maps/map_files/Temp Map Storage/Pahrump-Sunset - Outdated.dmm
  code/controllers/subsystem/nightcycle.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/lamp_post.dm
  code/modules/power/lighting.dm
  testing.dmm
Labels: test merged, feature addition, needs work, sprites

#164 adding the ambulance + truck + Jeep + Ballooooooooon
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/datums/components/crafting/recipes/vehicle_parts.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/equipment/tools/other_tools.dm
  code/game/mecha/equipment/weapons/mecha_ammo.dm
  code/game/mecha/equipment/weapons/weapons.dm
  icons/mecha/ambulance.dmi
  icons/mecha/buggy.dmi
  icons/mecha/jeep.dmi
  icons/mecha/jeepbos.dmi
  icons/mecha/jeepenclave.dmi
  icons/mecha/legionballoon.dmi
  icons/mecha/pickuptruck-mechanics.dmi
Labels: test merged, map changes, feature addition, faction changes, big iron port

#185 Removes cargo train in favor of old cargo
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
Labels: test merged, map changes, hot topic, feature removal, balance

#194 mutie rework yaaay
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/_onclick/item_attack.dm
  code/game/objects/items/fallout13misc.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/jobs/job_types/mutants.dm
  code/modules/mob/living/carbon/human/species_types/supermutant.dm
  code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
  code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
Labels: enhancement, test merged, feature addition, faction changes, balance, sprites

#196 Fixes enclave spawning with incorrect armor
  code/modules/jobs/job_types/enclave.dm
Labels: test merged, bug fix, faction changes, balance

#195 Various Fixes
  code/modules/clothing/suits/arfsuits.dm
  code/modules/power/cell.dm
  icons/obj/guns/projectile.dmi
Labels: test merged, bug fix, balance, sprites

#197 Cleans up Quirk descriptions
  code/datums/traits/good.dm
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
Labels: bug fix

#75 Sprite Addition: Stealth Boy + Variants
  code/game/objects/items/stealthboy.dm
  icons/fallout/objects/stealthboy.dmi
Labels: test merged, feature addition, sprites

#171 Wasteland Flipper Bugfix: Fixes double tile when placing tile on road turf
  fallout/turf/ground.dm
Labels: test merged, bug fix

#198 Tweaks plant+medicine bag item count, adds Bitter barrels, Fixes bottle rack
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/__DEFINES/inventory.dm
  code/datums/components/storage/concrete/bags.dm
  code/modules/farming/farming_structures.dm
  code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
  icons/fallout/farming/farming_structures.dmi
Labels: test merged, map changes, needs work, balance, sprites

#203 Uncomments out the crafting recipes for niche ammo types
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
Labels: test merged, feature addition, balance, big iron port

#205 Lets stronger mobs kill people
  code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
  code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
  code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
  code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
  code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
  code/modules/mob/living/simple_animal/hostile/f13/insects.dm
  code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
  code/modules/mob/living/simple_animal/hostile/f13/raider.dm
  code/modules/mob/living/simple_animal/hostile/f13/rattler.dm
  code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
  code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
Labels: test merged, balance

#208 Makes the Happyshark donator recipes avaible for everyone
  code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_wastefood.dm
  fallout/code/modules/client/loadout/donor.dm
  fallout/code/modules/fluff/happyshark_granter.dm
  fallout/code/modules/fluff/happyshark_recipe.dm
Labels: test merged, feature addition, Fluff

#215 S.P.E.C.I.A.L "S" and "P" Adjustments + 7.62 Ammo - Fixes Desert Ranger Armor
  code/__DEFINES/combat.dm
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/modules/clothing/custom/custom_clothing.dm
  code/modules/clothing/suits/arfsuits_unused.dm
  code/modules/mob/special_stats.dm
  code/modules/projectiles/ammunition/ballistic/rifle.dm
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
  code/modules/research/designs/ammolathe_designs.dm
  config/ooc_filter.txt
  hailmary.dme
Labels: bug fix, hot topic, balance

#214 Removes holes in map + Reduce spawns
  _maps/map_files/Baltimore/baltimore_surface.dmm
  _maps/map_files/Baltimore/baltimore_underground.dmm
  _maps/map_files/Baltimore/baltimore_upperlevel.dmm
Labels: map changes

#151 More train small changes
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/controllers/subsystem/nightcycle.dm
  code/datums/components/crafting/guncrafting.dm
  code/datums/traits/negative.dm
  code/game/machinery/doors/unpowered.dm
  code/game/machinery/radio_management.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/mecha_actions.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/loadout_beacons.dm
  code/modules/clothing/suits/arfsuits_unused.dm
  fallout/code/modules/client/loadout/head.dm
  modular_BD2/blacksmith/code/finished_items.dm
  modular_BD2/blacksmith/code/smithed_items.dm
  modular_BD2/legio_invicta/code/legio_invicta.dm
Labels: test merged, bug fix, map changes

#199 Conversion Kits + BoS changes (Ready for TM, work will continue)
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/__DEFINES/construction.dm
  code/__DEFINES/jobs.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/datums/traits/negative.dm
  code/game/machinery/computer/card.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/head/f13heavy_helmets.dm
  code/modules/clothing/suits/arfsuits.dm
  code/modules/clothing/under/accessories.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/enclave.dm
  code/modules/jobs/jobs.dm
  fallout/code/modules/client/loadout/head.dm
  icons/fallout/clothing/armored_heavy.dmi
  icons/fallout/onmob/clothes/armor_heavy.dmi
  icons/fallout/onmob/clothes/armor_power.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suit.dmi
  icons/obj/clothing/accessories.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: test merged, map changes, feature addition, faction changes, sprites

#212 Adds Ambulance, BOS Jeep, Normal jeep, and Legion Balloon
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Labels: test merged, map changes, feature addition, faction changes, balance, big iron port

#204 BCCM
  code/__DEFINES/subsystems.dm
  code/__HELPERS/text.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/bccm.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/bccm/tgui_asn.dm
  code/modules/admin/bccm/tgui_whitelist.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/ooc.dm
  hailmary.dme
  tgui/packages/tgui/interfaces/BCCMASNPanel.tsx
  tgui/packages/tgui/interfaces/BCCMWhitelistPanel.tsx
Labels: config changes, Tools

#217 Mutable Appearances Fix + Suits DM Changes
  code/datums/mutable_appearance.dm
  code/modules/clothing/suits/bigiron_suits.dm
  code/modules/clothing/suits/bigiron_suits_factions.dm
  hailmary.dme
Labels: bug fix, config changes, Merge Conflict

#216 Correct "sniper rifle magazine" ammo type as displayed in the ammolathe (308 -> 30-06)
  code/modules/research/designs/ammolathe_designs.dm
Labels: Merge Conflict

#211 Adds Handmade Rifle Variants to the game.
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/granters.dm
  code/modules/projectiles/boxes_magazines/external/rifle.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  icons/fallout/onmob/weapons/guns_lefthand.dmi
  icons/fallout/onmob/weapons/guns_righthand.dmi
  icons/obj/guns/projectile.dmi
Labels: enhancement, test merged, faction changes, balance
