Repository Foundation-19/Hail-Mary, pull requests merged in 2024-04, with the labels that each got.

#82 Removes Lick Healing & Special Tongues (not abductors just in case)
  code/__DEFINES/traits.dm
  code/__DEFINES/wounds.dm
  code/datums/traits/good.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/surgery/organs/tongue.dm
Labels: feature removal, stale

#43 loadouts
  fallout/code/modules/client/loadout/suit.dm
  fallout/code/modules/client/loadout/uniform.dm
Labels: bug fix, work-in-progress, stale

#86 Total unarmed balancing + quirk changes
  code/datums/traits/good.dm
  code/datums/traits/negative.dm
  code/datums/traits/neutral.dm
  code/game/objects/items/melee/f13onehanded.dm
Labels: feature removal, balance

#85 Map Addition: Legion Medical + IV now bugfree
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  icons/obj/iv_drip.dmi
Labels: map changes, big iron port

#91 Ultradense - Mobs Only
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: balance

#89 Tribal origin quirks now work
  code/datums/components/crafting/recipes/recipes_tribal.dm
  code/datums/traits/good.dm
Labels: enhancement, bug fix

#93 Weapon Tweaks
  code/__DEFINES/ammo.dm
  code/__DEFINES/combat.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
Labels: balance

#98 various final day tweaks
  code/game/objects/effects/spawners/f13lootdrop.dm
  code/game/objects/items/loadout_beacons.dm
  code/modules/projectiles/boxes_magazines/internal/revolver.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  icons/fallout/objects/guns/ballistic.dmi
  sound/f13weapons/ghoulgun_fire.ogg
Labels: feature addition, feature removal

#101 Bug Fix: Butchers table and Bandana Legion Fix
  code/game/objects/structures/tables_racks.dm
  code/modules/jobs/job_types/legion.dm
Labels: bug fix

#104 last minute fixes
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/game/machinery/dance_machine.dm
  code/modules/hydroponics/grown/random.dm
  code/modules/hydroponics/grown/tobacco.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/oasis.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/research/techweb/nodes/medical_nodes.dm
  code/modules/research/techweb/nodes/misc_nodes.dm
Labels: bug fix, map changes, feature removal, balance

#95 Port of a Port for Matrix Logging
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: config changes, big iron port

#102 LOOC Banning
  code/modules/admin/admin.dm
  code/modules/client/verbs/looc.dm
Labels: config changes, big iron port

#100 Admins Can Toggle Factions
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/job.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: config changes, big iron port

#106 More Loadoutfixes
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/loadout_categories.dm
  fallout/code/modules/client/loadout/head.dm
  fallout/code/modules/client/loadout/mask.dm
Labels: enhancement, bug fix

#108 legion fixes and more
  code/modules/jobs/job_types/eastwood.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  code/modules/projectiles/guns/ballistic/shotgun.dm
Labels: enhancement, balance

#99 Stim Delay + Super Stim Nerf
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/patch.dm
Labels: balance

#109 Major Map Update
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Labels: test merged, map changes

#111 Train's Rebase fixes
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/__DEFINES/radio.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/garbage.dm
  code/datums/components/crafting/recipes/recipes_forge.dm
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/datums/outfit.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/telecomms/machines/server.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/ghost_role_spawners.dm
  code/modules/hydroponics/grown/bloodleaf.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/mob/living/carbon/human/species_types/supermutant.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/guns/ballistic/rifle.dm
  fallout/areas/area.dm
  fallout/eris/code/gun_firemode.dm
  fallout/reagents/alcohol.dm
  fallout/turf/ground.dm
Labels: bug fix, map changes, config changes, balance, Merge Conflict

#110 various removals and fixes
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/hud/ghost.dm
  code/controllers/configuration/entries/general.dm
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/datums/traits/neutral.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/structures/flora.dm
  code/game/turfs/closed.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/carbon_sprint.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/emote.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/surgery/organs/vocal_cords.dm
  code/modules/vending/medical.dm
  code/modules/vending/snack.dm
  fallout/reagents/medicines.dm
Labels: bug fix, map changes, balance

#112 Train continuation
  _maps/RandomZLevels/VR/yuma_VR.dmm
  _maps/map_files/Pahrump-AB/Dungeons.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/__HELPERS/do_after.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/item_spawners.dm
  code/datums/datum.dm
  code/datums/progressbar.dm
  code/game/objects/items/storage/belt.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/view_variables/reference_tracking.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/verbs/ooc.dm
  code/modules/clothing/suits/arfsuits.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/supermutant.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/vending/megaseed.dm
  code/modules/vending/nutrimax.dm
  icons/obj/guns/projectile.dmi
  modular_BD2/blacksmith/code/furnace.dm
  modular_BD2/general/code/modular_BD2.dm
  modular_BD2/general/icons/tents.dmi
  modular_big-iron/code/game/machinery/radio_station.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tools/bootstrap/python37._pth
  tools/bootstrap/python_.ps1
Labels: enhancement, bug fix, map changes, balance

#97 S.P.E.C.I.A.L. pt. 2
  code/__DEFINES/jobs.dm
  code/__DEFINES/special.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/_onclick/item_attack.dm
  code/controllers/subsystem/job.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/special_stats.dm
  code/modules/projectiles/gun.dm
  fallout/obj/stack/f13Cash.dm
  fallout/obj/trash_stack.dm
  hailmary.dme
Labels: feature addition, config changes

#117 More small changes
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  code/datums/components/crafting/recipes/recipes_tailoring.dm
  code/modules/client/verbs/ooc.dm
  code/modules/clothing/custom/custom_clothing.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/arfsuits_unused.dm
  code/modules/jobs/loadout_ingame.dm
  code/modules/mob/dead/new_player/sprite_accessories/undershirt.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/supermutant.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/misc/medbeam.dm
  modular_BD2/legio_invicta/code/legio_invicta.dm
  tgui/packages/tgui/interfaces/LoadoutSelect.js
Labels: bug fix, config changes

#123 nothingbutpain (Town Clinic Changes)
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/modules/clothing/suits/arfsuits.dm
  code/modules/jobs/job_types/eastwood.dm
Labels: map changes, faction changes

#116 supposedly reduces lag
  code/__DEFINES/mobs.dm
  code/datums/wounds/bleed.dm
  code/datums/wounds/bones.dm
  code/modules/client/client_procs.dm
Labels: bug fix, CB port

#113 Fixes the road tiles missing textures
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Labels: map changes

#118 the first few balance changes
  code/__DEFINES/combat.dm
  code/datums/traits/good.dm
  code/modules/mob/special_stats.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  code/modules/projectiles/projectile/bullets/rifle.dm
Labels: feature removal, balance

#121 Wound Protection
  code/__DEFINES/armor.dm
Labels: balance

#125 Addition + Port: Backpacks Selection + Dark Durathread
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/backpack.dm
Labels: feature addition, big iron port

#126 Addition: Bandage First Aid
  code/game/objects/items/storage/firstaid.dm
  code/modules/jobs/job_types/legion.dm
Labels: feature addition

#127 Fixes bald centurions
  code/__DEFINES/access.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/jobs/job_types/legion.dm
  modular_BD2/legio_invicta/code/legio_invicta.dm
Labels: bug fix, sprites
