Repository Foundation-19/Hail-Mary, pull requests merged in 2024-10, with the labels that each got.

#223 Replaces jerrycan, fuel nozzle and mech fuel tanks sprites
  icons/mecha/mech_bay.dmi
Labels: sprites

#224 Less fast NCR Truck, Less tanky too, and less fuel consumated by the Legion balloon
  code/game/mecha/combat/phazon.dm
Labels: balance

#231 Removes zombie on Baltimore
  _maps/map_files/Baltimore/baltimore_surface.dmm
  _maps/map_files/Baltimore/baltimore_upperlevel.dmm
Labels: bug fix, map changes - baltimore

#227 Readds back flavortext minimum Requirement.
  code/__DEFINES/say.dm
  code/modules/mob/dead/new_player/new_player.dm
Labels: hot topic, Fluff

#226 Sprite Organization: Foods
  code/modules/food_and_drinks/food/customizables.dm
  code/modules/food_and_drinks/food/snacks/meat.dm
  code/modules/food_and_drinks/food/snacks_egg.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/food/snacks_other.dm
  code/modules/food_and_drinks/food/snacks_pastry.dm
  code/modules/food_and_drinks/food/snacks_sandwichtoast.dm
  code/modules/food_and_drinks/food/snacks_sushi.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  fallout/obj/food_and_drinks/food.dm
  icons/obj/food/canned.dmi
  icons/obj/food/egg.dmi
  icons/obj/food/food.dmi
  icons/obj/food/meat.dmi
  icons/obj/food/mexican.dmi
Labels: config changes, Fluff

#228 Fix BOS Knight Sergeant Spawn + Modify base and spawn.
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB-Upper.dmm
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
Labels: map changes - pahrump

#229 adds the Cushioned armor clothing flag, gives it to swat armor
  code/__DEFINES/_flags/item_flags.dm
  code/_globalvars/bitfields.dm
  code/datums/components/knockback.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/suits/bigiron_suits.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: work-in-progress, balance

#234 Update legion.dm - give Treasurer caps (500)
  code/modules/jobs/job_types/legion.dm
Labels: bug fix, balance

#237 Fix Auxillia payement
  code/modules/jobs/job_types/legion.dm
Labels: bug fix, balance

#232 Update recipes_misc.dm - fix sPA t45b recipe
  code/datums/components/crafting/recipes/recipes_misc.dm
Labels: bug fix

#230 Medium+ Armor Buffs
  code/__DEFINES/armor.dm
Labels: hot topic, balance

#239 Cushioned Armor Implementation
  code/__DEFINES/armor.dm
  code/modules/clothing/suits/bigiron_suits.dm
  code/modules/clothing/suits/bigiron_suits_factions.dm
Labels: test merged, feature addition, balance

#221 fix away mission for realsies
  code/controllers/subsystem/nightcycle.dm
Labels: bug fix

#240 Fixes the ghoul-bunker (found out they're invincible)
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
Labels: map changes - pahrump

#241 mild changes here and there. (small balance changes)
  code/game/objects/items/melee/f13powerfist.dm
  code/modules/jobs/job_types/bos.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
Labels: balance

#245 Small Fixes - Flak Vests, Mutant Speed Bug, Speed Walker
  code/datums/traits/good.dm
  code/modules/clothing/suits/bigiron_suits_factions.dm
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: bug fix, balance

#236 Update f13Cash.dm - restores spawning of NCR and Legion currencies
  fallout/obj/stack/f13Cash.dm
Labels: bug fix
