Repository Foundation-19/Hail-Mary, pull requests merged in 2024-05, with the labels that each got.

#128 readds keybinds
  code/modules/client/preferences.dm
Labels: bug fix, config changes

#107 Zipgun Reboring
  code/modules/projectiles/boxes_magazines/external/pistol.dm
Labels: enhancement, balance

#135 Trains balances
  code/__DEFINES/combat.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
  code/modules/projectiles/projectile/bullets/pistol.dm
  fallout/eris/code/gun_firemode.dm
Labels: balance

#129 Removes trekking from the entire codebase
  code/game/objects/items/granters.dm
  code/modules/jobs/job_types/eastwood.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
Labels: test merged, feature removal, faction changes, balance

#133 Comments out mutation toxins
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/slime_extracts.dm
Labels: test merged, feature removal

#130 Loadout Addition: Khanstuff in Loadout options
  code/modules/clothing/suits/arfsuits.dm
  code/modules/clothing/suits/arfsuits_unused.dm
  fallout/code/modules/client/loadout/head.dm
  fallout/code/modules/client/loadout/shoes.dm
  fallout/code/modules/client/loadout/suit.dm
  fallout/code/modules/client/loadout/uniform.dm
Labels: test merged, feature addition

#120 Fixes the rotation when holding certain weapons
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/plasmaf13.dm
Labels: test merged, to be tested

#131 New bunker, changes railroad bunker
  _maps/map_files/Pahrump-AB/Pahrump-AB-Lower.dmm
Labels: test merged, map changes, feature addition, feature removal

#137 Medicine Loadout Addition: Tribal Health Scanner + Tribal Surgery Loadout
  code/datums/components/crafting/recipes/recipes_medicine.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/loadout_toolkits.dm
  icons/obj/device.dmi
Labels: enhancement, test merged, feature addition

#138 Wasteland Flipper: House Wall DLC
  code/game/objects/items/crayons.dm
  fallout/turf/walls.dm
  icons/fallout/turfs/walls/house.dmi
Labels: test merged, feature addition, sprites

#139 Ranching kit redux
  code/game/objects/items/miscellaneous.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  fallout/icons/mob/horse.dmi
  fallout/icons/mob/mounts.dmi
Labels: test merged, feature removal, sprites

#140 Fixes Detective Loadout
  code/modules/jobs/job_types/eastwood.dm
Labels: test merged, bug fix

#141 Removes slime extracts from cargo
  code/modules/cargo/packs/security.dm
  fallout/code/modules/reagents/chemistry/recipes/fermi.dm
Labels: test merged, feature removal

#143 Shutters drop proper amount of prewar materials now when deconstructed
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/game/machinery/doors/poddoor.dm
Labels: test merged, bug fix, balance

#145 Ability to craft stock parts with craft menu
  code/datums/components/crafting/recipes/recipes_assemblies.dm
  code/game/objects/items/storage/boxes.dm
Labels: enhancement, test merged, feature addition, balance

#149 Senior Scribe and Scribe Bug Fix+Changes
  code/modules/jobs/job_types/bos.dm
Labels: test merged, bug fix, balance

#152 Fixes the 10mm speed loader sprite
  code/modules/projectiles/boxes_magazines/ammo_boxes.dm
Labels: test merged, bug fix, balance, sprites

#153 brahmin baron fix
  code/modules/jobs/jobs.dm
Labels: test merged, bug fix

#155 Adds the ability to flip eyepatches
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/head/f13head.dm
  icons/mob/clothing/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: enhancement, test merged, sprites

#156 Alerts admins upon door destruction
  code/game/machinery/doors/door.dm
  fallout/obj/structures/simple_door.dm
Labels: test merged, big iron port

#162 A compilation of small fixes
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/mecha/combat/phazon.dm
  icons/fallout/mobs/humans/fallout_npc.dmi
  icons/fallout/mobs/monsters/deathclaw.dmi
Labels: documentation, test merged, bug fix, sprites

#163 landmark fixes
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/game/objects/effects/landmarks.dm
Labels: test merged, bug fix, map changes

#154 Wasteland Flipper: Road Repairs
  code/game/turfs/f13concrete.dm
  fallout/turf/ground.dm
  icons/fallout/turfs/asphalt.dmi
Labels: test merged, feature addition, sprites

#165 Saving/Loading outfits
  code/datums/outfit.dm
  code/game/objects/items/cards_ids.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/outfits.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/projectiles/guns/magic.dm
  hailmary.dme
Labels: test merged, feature addition, config changes

#167 fixes n changes
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/game/objects/items/loadout_beacons.dm
  code/game/turfs/simulated/walls.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/job_types/ncr.dm
  code/modules/jobs/job_types/wasteland.dm
  code/modules/projectiles/projectile/beams.dm
  fallout/reagents/alcohol.dm
Labels: test merged, bug fix, map changes, balance

#136 balance tweaks - part 2
  code/__DEFINES/combat.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/modules/projectiles/guns/ballistic/automatic.dm
  code/modules/projectiles/guns/ballistic/pistol.dm
  code/modules/projectiles/guns/ballistic/revolver.dm
Labels: test merged, bug fix, map changes, feature removal, needs work, balance, sprites

#166 Ports the grace announcement from Big Iron
  code/controllers/subsystem/grace.dm
  hailmary.dme
Labels: test merged, feature addition, big iron port

#173 Fixes changing ghost sprites for BYOND members
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/observer/login.dm
  icons/mob/mob.dmi
Labels: test merged, bug fix, sprites

#176 Tribal QoL Additions
  code/datums/components/crafting/recipes/recipes_primal.dm
  code/datums/traits/good.dm
  fallout/code/modules/client/loadout/uniform.dm
Labels: test merged, config changes, faction changes

#134 Make deathclaws great again
  code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
Labels: needs work, balance

#170 Lets people who take berserker's rights use sutures
  code/datums/traits/good.dm
  code/game/objects/items/stacks/medical.dm
Labels: test merged, bug fix
