Repository Foundation-19/Hail-Mary, pull requests merged in 2025-07, with the labels that each got.

#292 Adjust: Remove Balitmore from Rotation
  config/maps.txt
Labels: config changes

#293 Adds: Zion Assets + Summer Flag for Holiday
  _maps/map_files/Tipton/Tipton-Surface-2.dmm
  code/game/objects/items/fallout13misc.dm
  fallout/areas/area.dm
  icons/obj/flags.dmi
  icons/turf/areas.dmi
  sound/ambience/wilderness.ogg
Labels: enhancement, Fluff

#268 Adding Lictorii (Orator/Auxilia Bodyguard)
  _maps/map_files/Pahrump-AB/Pahrump-AB.dmm
  code/__DEFINES/jobs.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/granters.dm
  code/modules/clothing/suits/bigiron_suits_factions.dm
  code/modules/jobs/job_types/legion.dm
  code/modules/jobs/jobs.dm
  icons/fallout/clothing/armored_light.dmi
  icons/fallout/onmob/clothes/armor_light.dmi
Labels: feature addition, hot topic

#274 Removes EMP Function on Proton Axe
  code/game/objects/items/melee/f13twohanded.dm
Labels: feature removal, opinion

#278 Legion Armor balance + Loadout rework
  code/modules/clothing/suits/bigiron_suits_factions.dm
  code/modules/jobs/job_types/legion.dm
Labels: hot topic, balance

#288 The Great Armor Rebalance
  code/__DEFINES/armor.dm
  code/modules/clothing/head/f13factionhead.dm
  code/modules/clothing/head/f13head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/bigiron_suits.dm
  code/modules/clothing/suits/bigiron_suits_factions.dm
Labels: faction changes, balance

#297 Map Adjust: Tipton
  _maps/map_files/Tipton/Tipton-Sky-3.dmm
  _maps/map_files/Tipton/Tipton-Surface-2.dmm
Labels: bug fix, map changes - tipton
